### PR TITLE
Go SDK: Validate that plugin is not using sdk forks

### LINKED ISSUE #315: SDK Validator: Fail go sdk forks
e.g.  go.mod

`replace [github.com/grafana/grafana-plugin-sdk-go](http://github.com/grafana/grafana-plugin-sdk-go) v0.260.3 => ./grafana-plugin-sdk-go`

### PR DESCRIPTION
**Pull request by academo**
Fixes https://github.com/grafana/plugin-validator/issues/315

### CODE REVIEW

File: pkg/runner/runner.go [hunk 1]
```diff
@@ -99,7 +101,12 @@ func Check(
 	return diagnostics, nil
 }
 
-func initAnalyzers(analyzers []*analysis.Analyzer, cfg *Config, pluginId string, severityOverwrite analysis.Severity) {
+func initAnalyzers(
```
Comment (academo) [inline pkg/runner/runner.go:104]: linting

File: pkg/runner/runner.go [hunk 2]
```diff
@@ -72,6 +72,8 @@ func Check(
 
 		seen[currentAnalyzer] = true
 
+		logme.DebugFln("Running analyzer %s", currentAnalyzer.Name)
```
Comment (academo) [inline pkg/runner/runner.go:75]: adding this for local debugging

**Review by andresmgot — APPROVED** [review]
LGTM
